# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build:

    runs-on: macos-latest
    env:
      EP_GH_IGNORE_TIME: true
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: sudo rm -rf node_modules && yarn install --immutable --immutable-cache --check-cache
    - name: Build/release Electron app
      uses: michalzaq12/action-electron-nuxt@v1.5.0
      with:
        mac_certs: ${{ secrets.MAC_CERTS }}
        mac_certs_password: ${{ secrets.MAC_CERTS_PASSWORD }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
        release: false
    - uses: actions/upload-artifact@v3
      with:
        name: synth-mac-setup
        path: ./build/setup-0.0.1.dmg
      
